# ================================================
# Azure Key Vault - Secrets Integration with AKS
# ================================================
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" 
    keyvaultName: "uzma-sami-key-vault" # <-- Updated to match your created Vault
    tenantId: "7ca42589-ff83-499a-bbeb-7e32ee5563db"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: api-key
          objectType: secret